### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by CostantinoGrana** [fencl/whale#1]
I think that `vp8l_cannonical_code` is misspelled. Dictionaries agree on *canonical* with a single *n*. Anyway, I loved your code. The only complaint, if any, would be about the excessive compactness, which makes it harder to debug and use in teaching environments.

**Comment by fencl** [comment]
First of all, thank you for your interest. You are correct, I have fixed the spelling. You are also very much on point with the compactness, this implementation would be horrible as a learning resource. I wrote it with the intention to be able to quickly embed the decoder into other projects.
